### ISSUE TITLE
deploy-last ignores entity option

### ISSUE THREAD

**Issue by gtfierro** [immesys/spawnpoint#13]
If one uses the `--entity` flag to specify the BOSSWAVE entity to use on a `deploy` invocation in spawnctl, `deploy-last` fails to remember the use of that flag. The result is that `deploy-last` may complain about the lack of an entity or use whatever is in `$BW2_DEFAULT_ENTITY`

**Comment by jhkolb** [comment]
`deploy-last` should respect entities more cleanly now.

I also switched the internal serialization format from `msgpack` to `gob`. This does mean that old history files are incompatible with the newest version of `spawnctl`. If you encounter errors, you'll need to delete your history file, most likely stored as `~/.spawnpoint_history`.
