### ISSUE TITLE
s/useHostNet/allowHostNet/

### ISSUE THREAD

**Issue by immesys** [immesys/spawnpoint#27]
Installer creates yml file with invalid key.

Also installer leaves a config.ymle file, sed backup maybe?

**Comment by jhkolb** [comment]
The invalid key problem is now fixed.

The installer checks if `/etc/spawnd/config.yml` exists and, if so, leaves it alone. Or at least it's supposed to. @immesys, does that not match up with the behavior you saw when using the installer?

**Comment by immesys** [comment]
After running the installer, I was left with `/etc/spawnd/config.yml` and `/etc/spawnd/config.ymle` where the latter did not have the substitutions made

**Comment by jhkolb** [comment]
Lol, oops I misunderstood your original comment. Yeah, it was because I was using `sed -ie`. I changed that so it shouldn't generate the extra file anymore.
