### ISSUE TITLE
Installer adds burst

### ISSUE THREAD

**Issue by immesys** [immesys/spawnpoint#28]
It would be better if the installer did not specify startlimitinterval and burst otherwise if there is some failure (e.g a powercut in soda) then spawnpoints will not start up afterwards because they will enter systemd failed mode.

**Comment by jhkolb** [comment]
Lol, I'm pretty sure I added these in after the bandwidth fiasco at the garber deployment (which ended up being mongo and not spawnd anyways).

I've removed them, so future installs won't include `StartLimitInterval` or `StartLimitBurst` in their unit files. And, these fields will be removed from existing unit files when you use the installer to update `spawnd` as well.
