### ISSUE TITLE
Expose serial devices in spawnpoint container

### ISSUE THREAD

**Issue by gtfierro** [immesys/spawnpoint#30]
Devices such as the EMU2 report over a serial port, and it would be great if the deploy file exposed some way to include/mount local directories inside the spawnpoint container.

Does this exist? Its not quite the same as the "includedFiles" feature

**Comment by immesys** [comment]
Exposing a serial port is not the same as exposing a local directory. The former requires `--device /dev/ttyX` whereas the latter is a volume mount. You cannot (should not?) volume mount a serial device into an unprivileged container.

**Comment by immesys** [comment]
I recently just had to address this issue for the hamilton testbed.

**Comment by gtfierro** [comment]
Ah, ok. Good to know.

**Comment by jhkolb** [comment]
Sounds like the consensus is not to allow serial devices to be exposed.

**Comment by gtfierro** [comment]
I think we do, just not as a volume mount. We should use the `--device /dev/ttyX`

**Comment by jhkolb** [comment]
I've pushed code that lets you specify a specify a `devices` field in a service configuration YAML file. For example:
```yaml
devices: ["/dev/tty4", "/dev/tty8", "/dev/tty15"]
```
The strings refer to the device's path on the host, which will be the same as its path within the container.

However, it seems to me that this has some pretty important security implications, just like host networking. So, would it be worthwhile to have this disabled by default, and require someone to explicitly authorize this in the configuration file for `spawnd`? This would be just like our current approach to the host networking issue.

Thoughts?

**Comment by immesys** [comment]
I think that's a good solution, and we can use wave3 dots for those permissions down the line

**Comment by gtfierro** [comment]
We could use wave2 dots for these now because they are paths and fit cleanly into what DoTs can express

**Comment by jhkolb** [comment]
For now, let's go with a solution that replicates what we have for host networking. This will be simpler to implement and lets us deploy drivers that may need this functionality sooner rather than later.

However, we could certainly use Wave2 dots for this in the future.
