### ISSUE TITLE
MergeMetadata needs URI argument?

### ISSUE THREAD

**Issue by gtfierro** [immesys/spawnpoint#4]
Currently, the spawnable.MergeMetadata method will create BW Metadata messages on `<svc_base_uri>/!meta/<keyname>`, which, if we are following the URI scheme at https://github.com/immesys/bw2/wiki/Drivers#uris, then this adds Metadata to _all_ services with the same name. 

My proposal is we add the ability (either through a new method or new argument) to specify the URI on which metadata is merged from the `params.yml` file. It is probably more likely that a user will want to place metadata on the instance or interface or signal in the URI rather than on the shared service name.

Thoughts? @jKolb1

**Comment by jhkolb** [comment]
Fixed in #5 .
